### ISSUE TITLE
implement a way to get all solutions for a given predicate

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#10]
so far, calling Z3's check method returns only one model for the given query. We should implement a way to generate all solutions for a given predicate. this method will probably be used often, so a helper class in the backend package might be useful.

Perhaps we should start with a test case computing all solutions to a simple query such as "1 < x & x < 5"

**Comment by x-moe-x** [comment]
I implemented a basic version of a solution finder, inspired by two stackoverflow.com answers. It is basically a brute force approach with a max number of iterations.
