### ISSUE TITLE
implement equalAst(...) Method to enable Node being checked for equality

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#101]
- [x] add `boolean equalAst(Node node)` to `Node`

- [x] overwrite `equalAst(Node node)` in every subclass

**Comment by x-moe-x** [comment]
ok, it's not that easy... see  [ BecomesElementOfSubstitutionNode ](https://github.com/hhu-stups/bmoth/blob/develop/src/main/java/de/bmoth/parser/ast/nodes/BecomesElementOfSubstitutionNode.java): two Nodes of this type both should contain the same `List<IdentifierExprNode> identifiers`, but that might be hard to check considering different ordering of the same list of identifiers...

Implementing `equals(...)` and `hashCode(...)` using data that is accessible from the outside (for example ignoring `terminalNode` in [IdentifierExprNode](https://github.com/hhu-stups/bmoth/blob/develop/src/main/java/de/bmoth/parser/ast/nodes/IdentifierExprNode.java)) would enable us to use a `Set` instead of a list which would make comparison very easy.

**Comment by wysiib** [comment]
Guess we can just rely on the order here: `x+1` does not have the same AST as `1+x`, which is fine I think.
Of course one could think about normalising the AST, but that should be a separate step.
