### ISSUE TITLE
implementiert Tarjan's strongly connected components algorithm

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#103]
[Tarjan's algorithm](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm)

**Comment by x-moe-x** [comment]
one could also think about using http://jgrapht.org/ for graph processing, which incorporates tarjans algorithm already as well as others...

**Comment by wysiib** [comment]
why not. i think it won't be that hard to just insert discovered states into one of jgrapht's graph representations. no need to reinvent the wheel.

**Comment by x-moe-x** [comment]
it should also be possible to not use `State.predecessor` or `StateSpaceNode.successors` (or the wrapping of `State` in `StateSpaceNode`) and to use a `Graph<State, DefaultEdge>` altogether.

**Comment by wysiib** [comment]
Even better. I assume the creators of JGraphT know more about graph representations than we do. If it is not to cumbersome, we should switch over.

**Comment by wysiib** [comment]
done by including library
