### ISSUE TITLE
Find / Implement a way to store preferences

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#11]

**Comment by wysiib** [comment]
https://docs.oracle.com/javase/8/docs/technotes/guides/preferences/index.html

**Comment by Lunnaris01** [comment]
Implemented using JAXB

**Comment by Lunnaris01** [comment]
The shown FileNotFoundExeption is only shown for information purposes and handled if anyone is stumbling upon it while testing. The file is uploaded, however feel free to delete and test, preferences are saved and the XML File is created on leaving the App.

**Comment by Jessypet** [comment]
9964337
