### ISSUE TITLE
finalise simple model checking algorithm

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#21]

**Comment by wysiib** [comment]
![img_1366](https://cloud.githubusercontent.com/assets/1465305/25545639/06ef562a-2c60-11e7-89e5-5acc9ab5486e.JPG)
<img width="659" alt="screen shot 2017-04-28 at 22 13 33" src="https://cloud.githubusercontent.com/assets/1465305/25545625/fbae72b4-2c5f-11e7-84bb-41e8347027e3.png">

**Comment by x-moe-x** [comment]
I think I'm a little bit stuck here... I tried to adapt changes until  e743bb35044fe87074bc543be2361e73e7b5a806 from @dohan into 66d7d1eb22a29b791d207fc1de757c0d25c7d5da but I'm not sure how to proceed from here, for example when to use "primed variables" and how to perform a correct invariant check...

**Comment by wysiib** [comment]
Let's see if we can clear things up:
A primed variable is, basically, a variable with an ' at the end of its name. That is, the primed version of the variable x is the variable x'.
Usually, they are used to distinct current values of variables from the ones in the next state of the system.

Consider the transition x:=x+1, if executed in a state where x=2.
We want to use Z3 to compute the next value of x. However, we can not simply use a conjunction:
x = 2 & x = x+1 is false.
To work around this issue, we use the primed version of x to denote the value in the next state:
x = 2 & x' = x+1 is satisfiable and x' receives the values 3 as intended.
The ' is later removed when a new state is constructed (see stateFromModel).

Checking the invariant can be done by searching for a solution to the invariant given the current state. If the invariant is x<5, we can check it in the state where x=2 by solving
x = 2 & x < 5 in Z3. If the predicate is satisfiable, the invariant holds.
If it is not satisfiable, e.g., in the state where x=6, the invariant is violated.

**Comment by wysiib** [comment]
Just ask again if anything remains unclear.

**Comment by x-moe-x** [comment]
For invariant checking: It's not enough to just add it to the solver and check satisfiability?

**Comment by wysiib** [comment]
That should be sufficient. However, the solver needs to know in which state it is!
Adding only the invariant to Z3 makes it find different solutions:
x < 5 causes it to enumerate 4, 3, 2, 1, ....
If you add the current state (say x=2) to the solver as well, the invariant is checked for that particular state.
