### ISSUE TITLE
implement FormulaTranslator::visitSingleAssignSubstitution(...)

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#24]
FormulaTranslator is lacking an implementation of visitSingleAssignSubstitution(...)

**Comment by dohan** [comment]
If we implement this method, then we should rename the class (e.g. Z3Translator).
The implementation already exists in ModelChecker::doModelCheck.

**Comment by wysiib** [comment]
I think this should be a separate translator, see my comment in #23

**Comment by x-moe-x** [comment]
I suggest to either close this issue or move it to testing and assign it to @dohan

**Comment by dohan** [comment]
visitSingleAssignSubstitution has been implemented in MachineToZ3Translator
