### ISSUE TITLE
In case a counterexample is found it should be presented to the user

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#37]
Our model checker is able to identify invariant violations in the first example models. 👍 
However, the path to the invariant violation is not reported to the user.

I think we should replace the boolean return value of the model checking method by a custom object including the path to the counterexample. Maybe we should introduce a class ModelCheckingResult, which can then be "correct" "counterexample + path" and "timeout"?

**Comment by x-moe-x** [comment]
A first version could be the last state as it forms the top of a stack via it's predecessor

**Comment by Jessypet** [comment]
> which can then be "correct" "counterexample + path" and "timeout"

timeout?

**Comment by wysiib** [comment]
I assume we might run into a predicate Z3 cannot solve. Maybe we should just wait until it happens and see how we handle it?

**Comment by Jessypet** [comment]
Simple version is done. The result is either "correct" or the invalid state and the path to it.
