### ISSUE TITLE
Support set theory

### ISSUE THREAD

**Issue by dohan** [hhu-stups/bmoth#4]
Needed operators:
- set constructor, e.g. {1,2,3}
- set comprehension {x | x : 1..10 & x mod 2 = 0}
- domain, range, union...

**Comment by wysiib** [comment]
we need set membership as well!

**Comment by wysiib** [comment]
Translating set comprehensions to Z3 is rather hard, as there is no direct support for them in Z3. Any ideas how we can represent them instead?

**Comment by x-moe-x** [comment]
Set membership and range is also blocking #21

**Comment by wysiib** [comment]
mkSetSubset in Z3 is the <=. Non-equality can be done by adding != manually.

**Comment by wysiib** [comment]
I think we shoul close this issue and add more specific ones for missing translations. Otherwise, this will probably never be finished.

**Comment by jhoepen** [comment]
Union case tested. Domain and range cases moved to seperate issues.
