### ISSUE TITLE
REPL for B

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#41]
Prof. Leuschel requested a separate window with a REPL, where he can input B predicate and receive a model or "unsatisfiable" as an answer.

A simple interaction could look like this:
>> x = 3 & y > x
{x = 3, y = 4}
>> x = 3 & y = 3 & y /= x
UNSATISFIABLE

this is useful for testing purposes but not needed for model checking.

**Comment by Jessypet** [comment]
See #76a3b56
