### ISSUE TITLE
Add preference for integer sizes

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#44]
To distinguish NAT and NATURAL as well as INT and INTEGER, B uses MIN_INT and MAX_INT.
The idea is do have 
* NATURAL = all the natural number there are
* NAT = the "implementable" natural numbers, i.e. 0 to MAX_INT
the same approach is used for the integer numbers.

We should have two preferences "Min Integer" and "Max Integer", changeable using the UI.
The preferences should be honored in the translation of NAT and INT.

Steps to do:
- [x] Introduce two preferences
- [x] Add UI for changing them
- [x] Ensure the user can only input valid values
- [x] Use the preference in the translation

**Comment by jhoepen** [comment]
Tested and working, although errors for out of range input appear as "needs to be numeric"

**Comment by Lunnaris01** [comment]
Changed "Needs to be numeric" to "Not Numeric or out of Integer-Range:" to be more informative
