### ISSUE TITLE
implement cartesian product

### ISSUE THREAD

**Issue by Mareikes** [hhu-stups/bmoth#46]
Cartesian Product S * T={x,y| x:S & y:T } needs to be implemented

**Comment by dohan** [comment]
The '*' operator is ambiguous within the B language. Hence, it requires some work in the type checker.

**Comment by dohan** [comment]
The '*' operator is already implemented in the type checker (77c08eb0d86dccafacc946303eea73ae8af76d55). It remains to implement the CARTESIAN_PRODUCT case in the FormulaToZ3Translator.
