### ISSUE TITLE
Parser does not accept PRE substitution

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/bmoth#60]
The parser does not seem to accept the PRE THEN END substitution.
Something like
  IncX = PRE x<50 THEN x := x+1 END;
in ArithmeticLaws.mch leads to an exception.
It would be good to also show the line number of the parse error.

**Comment by dohan** [comment]
line numbers were added by cee8d6ee8cb59f697004950ea4a94b1309e76df6
