### ISSUE TITLE
z3 power function leads to nonlinear real arithmetic, colliding with quantifier formula

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#67]
see from #59

**Comment by x-moe-x** [comment]
using a custom, recursive power function makes the originating problem satisfiable again 
```z3
; prepare pow(a,b) = a ^ b
(define-fun-rec pow ((a Int) (b Int)) Int
  (ite (= 0 b)
    ; a ^ 0 = 1
    1    
    (ite (= 0 (mod b 2))
      ; b even
      (* (pow a (div b 2))(pow a (div b 2)))
      ; b odd
      (* a (pow a (- b 1)))            
    )
  )
)
; prepare set = {1,2}
(declare-const set (Array Int Bool))
(assert (= set (store (store ((as const (Array Int Bool)) false) 1 true) 2 true)))
; prepare x
(declare-fun x () Int)
(assert (= (pow x 2) (* x x)))
; assert existence of y with y U set = set
(assert (exists ((y Int)) (let ((setUnion ((as union (Array Int Bool)) (store ((as const (Array Int Bool)) false) y true) set)))(= setUnion set))))
(check-sat)
```

**Comment by x-moe-x** [comment]
We can not define a (recursive) function directly, so using (obtained via `Context::parseSMTLIB2String(..)`):
```z3
(declare-fun pow (Int Int) Int)
(assert (forall ((a Int) (b Int))
  (! (let ((a!1 (ite (= 0 (mod b 2))
                     (* (pow a (div b 2)) (pow a (div b 2)))
                     (* a (pow a (- b 1))))))
       (= (pow a b) (ite (= 0 b) 1 a!1)))
     :pattern ((pow a b))
     :qid |:rec-fun|)))
```

**Comment by x-moe-x** [comment]
51f562958959df96649a40b528e5761eae98d748 makes all tests pass, but is it a good idea to go this way?

**Comment by wysiib** [comment]
In fact, we have no idea if this is the way to go. So far, nobody has implemented a full-blown model checker for B using Z3. In consequence, the question how best to encode exponentiation has not been answered yet. This is the first commit really hitting an open research questions.

**Comment by wysiib** [comment]
In the long run, different encodings have to be compared thoroughly. Furthermore, we might set up both translations at once and let Z3 pick the way to proceed?
