### ISSUE TITLE
SolutionFinder::findSolutions(...) returns multiple models for the same associated State

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#68]
This problem leads to failing of `Issue59Test::testIssue59WithAdditionalInvariant()`
It would be a good idea to extract States from Models before entering the add-to-queue-if-not-visited-loop

**Comment by x-moe-x** [comment]
see [ModelChecker.java#L69](https://github.com/hhu-stups/bmoth/blob/41a80cb10929077db32359b1bc26d5d21ea6c9ed/src/main/java/de/bmoth/modelchecker/ModelChecker.java#L69)

**Comment by x-moe-x** [comment]
Problem originates from 41a80cb10929077db32359b1bc26d5d21ea6c9ed because `invariant` now stays inside of `solver` all the time. Debugging `Issue59Test::testIssue59WithAdditionalInvariant()`, it becomes clear that `ModelChecker` does a lot of redundant work because multiple models are generated for the same state.

**Comment by wysiib** [comment]
The invariant should not be asserted when searching for a successor state. Maybe we should have different solver objects for invariant checking an computation of successors?

**Comment by wysiib** [comment]
Maybe even an instance of solver for each operation? Then we could only assert the current state and nothing else has to be reloaded?

**Comment by x-moe-x** [comment]
b0abec260cd7309f9e8d374aed404cb80ca53df4 introduces separate solvers / finders for invariant checking and next state computation

**Comment by wysiib** [comment]
see also bf192209bd5565cfcbe05b96a8301ea2d4a89ddd, due to quantified variables, some states were discovered multiple times
