### ISSUE TITLE
Parser does not support ~ (relational inverse)

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/bmoth#72]
p = {3|->5, 3|->9, 6|->3, 9|->2} &  q =p~

in REPL gives

Parse error: Unexpected input '~' in line 1 column 168.
Additional information: mismatched input '~' expecting {<EOF>, EQUIVALENCE, IMPLIES, '&', 'or'}
Exception in thread "JavaFX Application Thread" Parse error: Unexpected input '~' in line 1 column 168.run

**Comment by dohan** [comment]
'~' is not yet supported by the Z3 translator

**Comment by wysiib** [comment]
should be supported now
