### ISSUE TITLE
SolutionFinder throws Exception if predicate is SAT without a model

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#73]
For instance, the predicate "1<2" is satisfiable. However, no variables are set.
The SolutionFinder tries to compute a second solution and runs into an exception.

The issue is the cause of #71.

**Comment by wysiib** [comment]
See 6baccc4 for a test case

**Comment by Lunnaris01** [comment]
Seems to work.
Does this ever occur in actual machines? Currently gives "UNSATISFIABLE" or no solutions. We should discuss what behaviour we want from the modelchecker/REPL #71
