### ISSUE TITLE
UI: Button to stop model check

### ISSUE THREAD

**Issue by Mareikes** [hhu-stups/bmoth#75]

**Comment by Mareikes** [comment]
if we got an infinite model where our model checker can't find any violations we should be able to halt the check manually

**Comment by x-moe-x** [comment]
Is it necessary to make doModelCheck(...) interuptable?

**Comment by wysiib** [comment]
maybe we should make it run in a thread, and put a progress bar in front?

**Comment by x-moe-x** [comment]
But how to know about the progress?

**Comment by Lunnaris01** [comment]
I think some icon showing the process is running would be a good Idea.

**Comment by Lunnaris01** [comment]
Seems like Machines with even more than 10000 models just stop.

**Comment by wysiib** [comment]
we can't tell about the progress as we do not know how many states will be found eventually. Maybe just some process bar showing that something is happening? Even better, we could have a dialog showing the current size of the queue and the number of states analysed so far.

**Comment by Lunnaris01** [comment]
We might need change the Modelchecker to work as interruptable thread.

**Comment by x-moe-x** [comment]
I will implement a method to stop the current checking session, so the executing thread can stop checking on being interrupted.

**Comment by x-moe-x** [comment]
Model checking can be aborted via `ModelChecker::abort()` now.
