### ISSUE TITLE
The BMothPreferences don't accept negative numbers

### ISSUE THREAD

**Issue by heinzware** [hhu-stups/bmoth#77]
The OptionController uses the method **_StringUtils.isNumeric()_**. If you look a the documentation of this method, you will see it only excepts CharSequennces that contain only Unicode digits:

_Checks if the CharSequence contains only Unicode digits._

Because of this, the BMothPreferences only accept positive numbers.

**Comment by wysiib** [comment]
fixed in 628daac04897ae0b064aad1c65e86a86de5955eb
