### ISSUE TITLE
OptionControllerTest results are inconsistent

### ISSUE THREAD

**Issue by heinzware** [hhu-stups/bmoth#78]
Startet the task **_uiTest_** 3 times in a row and got 3 different results:
![bildschirmfoto vom 2017-05-25 16-31-56](https://cloud.githubusercontent.com/assets/22413633/26454921/c7deddd4-4168-11e7-94cf-c9bfc32692cd.png)
![bildschirmfoto vom 2017-05-25 16-34-34](https://cloud.githubusercontent.com/assets/22413633/26454927/cbe55408-4168-11e7-9f84-d4893fcd2766.png)
![bildschirmfoto vom 2017-05-25 16-35-55](https://cloud.githubusercontent.com/assets/22413633/26454930/ceb3d876-4168-11e7-8abf-61133973c9e4.png)

It seems that this code doesn't produce consistent results:
`hasText(String.valueOf(BMothPreferences.getIntPreference(BMothPreferences.IntPreference.MIN_INT)))`

**Comment by wysiib** [comment]
i think this might be caused by the way stages are used in the OptionController. The test does not use the stage given in the parameter. Maybe we should refactor the options to work the same way the repl does, i.e. use initializable?
