### ISSUE TITLE
Machine: Initialisation does not apply constraintList

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#89]
The machine PinDownPowProblem.mch tries to initialize `x := 10**5`. This leads to arbitrary values of `x`.

The cause of the problem seems to be that `FormulaToZ3Translator`'s `constraintList` is not applied during processing of `MachineNode::getInitialisation()`. So `(POWER_OF 10 5)` can be anything.

Would it a good idea to enable `FormulaToZ3Translator` to process and hand out accumulated constraints apart from inside of `translatePredicate(...)`-methods? This way they could be applied where needed, like basic input for relevant solvers?

**Comment by x-moe-x** [comment]
This problem might also arise for using `NAT`, `NATURAL`, `NATURAL1` and `INT`

**Comment by wysiib** [comment]
I think the translate predicate .... methods should be complete. Splitting translation and extra constraints might cause more errors because someone might forget!
