### ISSUE TITLE
show the content of a selected file in the source window

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#9]
currently blocked by #8 

after we can select and open a file, the source code should be displayed

**Comment by Lunnaris01** [comment]
Clearing the Old Content/Pressing Backspace in an Empty file causes Exception:
java.lang.IllegalStateException: Cannot get the type of a change that neither inserts nor deletes anything.

**Comment by wysiib** [comment]
This issue seems to be cause by a problem in the editor component: TomasMikula/RichTextFX#481
Once they release an update, it should be fixed
