### ISSUE TITLE
Parse exception for machine

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/bmoth#91]
I get  the following error
Caused by: Parse error: Unexpected input '(' in line 7 column 5.
Additional information: mismatched input '(' expecting EQUAL
        at de.bmoth.parser.ErrorListener.syntaxError(ErrorListener.java:17)
for this machine:
```
MACHINE DefSetTest1
SETS DS
VARIABLES x, y, z
INVARIANT x<2 & y:{0,1} & z:{0,1}
INITIALISATION x:=0 || y:= 0 || z:=0
OPERATIONS
 inc1(a,b) = SELECT a:DS & b:DS & a/=b & y=0 THEN x:=x+1 || y := 1 END;
 inc2(a) = SELECT a:DS & z=0 THEN x:=x+1 || z := 1 END
END
```

**Comment by wysiib** [comment]
I don't think operations with parameters are supported yet, @dohan?
The Select substitution should work though.

**Comment by leuschel** [comment]
Is existential quantification supported?

**Comment by wysiib** [comment]
yes
