### ISSUE TITLE
implement LTL model checking

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#96]
Involves different subtasks:
- [x] translate / rewrite LTL formula to an equivalent formula only using U (Until) and X (Next) operators
- [x] translate / rewrite LTL formula, move negation to the included B formulas
- [x] generate Büchi automaton representing negated formula
- [x] connect to model checker

**Comment by jhoepen** [comment]
For now I will focus on the LTL translation part

**Comment by jhoepen** [comment]
Second subtask done, still needs testing

**Comment by Mareikes** [comment]
Re first task: Removed dependency on Globally and Finally, now we only need Until, neXt, Weak until.

for testing that in testTransformationOfGlobally() we get a de.bmoth.parser.ast.nodes.ltl.LTLKeywordNode@ (some arbitrary number)  when expecting false. This node is of Kind FALSE, how do we repair the test?

**Comment by Mareikes** [comment]
Also, most tests of tasks 2 need to be re-written as we changed the output when eliminating globally and finally

**Comment by wysiib** [comment]
just connected everything to the model checker. there are still some issues in the translation, but we can open separate items for them
