### ISSUE TITLE
Parser parses LTLPrefixOperatorNode as LTLBPredicateNode

### ISSUE THREAD

**Issue by Mareikes** [hhu-stups/bmoth#99]
example in not( {...} U {...}) , possibly for other cases as well (weak_until)

in LTLTransformationTest.java

**Comment by dohan** [comment]
There is no ignored unit test in LTLTransformationTest.java. Is the issue out-dated? Otherwise, can you provide a unit test.

**Comment by wysiib** [comment]
duplicate of #100
